### ISSUE TITLE
Bibliography here or at PubPub

### ISSUE THREAD

**Issue by venkatachalapathy** [IngenuityArts/specscape#5]
@WheezePuppet , @IngenuityArts and @srikanthmudigonda ,

Do you want to maintain a bibliography of this project fork here or in our PubPub community?

**Comment by srikanthmudigonda** [comment]
Pubpub might make it easier?

**Comment by venkatachalapathy** [comment]
See [related issue](https://github.com/WheezePuppet/specnet/issues/10). I think we are in agreement.
